### ISSUE TITLE
Question: Linux 4.4?

### ISSUE THREAD

**Issue by frap129** [ramosian-glider/clang-kernel-build#3]
Will these paches and scripts work for compiling 4.4? Ive seen references to 4.7 and the readme says 4.12, but I'm unsure about 4.4. Thanks!

**Comment by ramosian-glider** [comment]
You can try these patches out, but most certainly they won't work on 4.4 out of the box. You'll need to cherry-pick a couple of other upstream patches that are labeled "clang:". 
The list of patches at http://llvm.linuxfoundation.org/index.php/Main_Page may also help.

Overall, I'm mostly interested in upstream kernels working with Clang (because of testing with e.g. http://github.com/google/kmsan), doing backports doesn't sound worthwhile.

**Comment by ramosian-glider** [comment]
Closing this issue, feel free to reopen if you have further questions.
